-- Widens the content columns Prisma declared as a bare String, which MySQL
-- stores as varchar(191) and silently truncates because sql_mode has no
-- STRICT_TRANS_TABLES. Generated by laravel/storage/framework/make-widen.js;
-- the matching @db.Text annotations were added to prisma/schema.prisma at the
-- same time, so the two agree.
--
-- Indexed columns are deliberately absent: a UNIQUE slug needs a prefix length
-- to become TEXT, and a foreign key must match the column it references.
--
-- 80 statements, all of them widenings — no data is lost by
-- running this, and it is safe to re-run.

ALTER TABLE `aboutcontent` MODIFY `heroTitle` TEXT;
ALTER TABLE `aboutcontent` MODIFY `heroSubtitle` TEXT;
ALTER TABLE `aboutcontent` MODIFY `storyTitle` TEXT;
ALTER TABLE `aboutcontent` MODIFY `storyBody` TEXT;
ALTER TABLE `aboutcontent` MODIFY `missionText` TEXT;
ALTER TABLE `aboutcontent` MODIFY `visionText` TEXT;
ALTER TABLE `aboutcontent` MODIFY `valuesText` TEXT;
ALTER TABLE `aboutcontent` MODIFY `timelineData` TEXT;
ALTER TABLE `blogcategory` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `blogpost` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `blogpost` MODIFY `excerpt` TEXT NOT NULL;
ALTER TABLE `blogpost` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `blogpost` MODIFY `seoTitle` TEXT;
ALTER TABLE `blogpost` MODIFY `seoDescription` TEXT;
ALTER TABLE `contactmessage` MODIFY `subject` TEXT;
ALTER TABLE `contactmessage` MODIFY `message` TEXT NOT NULL;
ALTER TABLE `faqitem` MODIFY `question` TEXT NOT NULL;
ALTER TABLE `faqitem` MODIFY `answer` TEXT NOT NULL;
ALTER TABLE `gallery` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `gallery` MODIFY `description` TEXT;
ALTER TABLE `galleryimage` MODIFY `altText` TEXT;
ALTER TABLE `globalsettings` MODIFY `tagline` TEXT;
ALTER TABLE `globalsettings` MODIFY `address` TEXT;
ALTER TABLE `globalsettings` MODIFY `footerText` TEXT;
ALTER TABLE `globalsettings` MODIFY `copyrightText` TEXT;
ALTER TABLE `globalsettings` MODIFY `seoTitle` TEXT;
ALTER TABLE `globalsettings` MODIFY `seoDescription` TEXT;
ALTER TABLE `globalsettings` MODIFY `seoKeywords` TEXT;
ALTER TABLE `globalsettings` MODIFY `ctaText` TEXT;
ALTER TABLE `heroslide` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `heroslide` MODIFY `subtitle` TEXT;
ALTER TABLE `heroslide` MODIFY `buttonText` TEXT;
ALTER TABLE `impactstat` MODIFY `label` TEXT NOT NULL;
ALTER TABLE `impactstat` MODIFY `description` TEXT;
ALTER TABLE `islamicmessage` MODIFY `arabicText` TEXT;
ALTER TABLE `islamicmessage` MODIFY `translation` TEXT NOT NULL;
ALTER TABLE `media` MODIFY `altText` TEXT;
ALTER TABLE `membershipapplication` MODIFY `address` TEXT;
ALTER TABLE `membershipapplication` MODIFY `motivation` TEXT;
ALTER TABLE `membershipapplication` MODIFY `documents` TEXT;
ALTER TABLE `membershipcategory` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `membershipcategory` MODIFY `description` TEXT;
ALTER TABLE `membershipcategory` MODIFY `requirements` TEXT;
ALTER TABLE `membershipcategory` MODIFY `benefits` TEXT;
ALTER TABLE `newscategory` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `newspost` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `newspost` MODIFY `excerpt` TEXT NOT NULL;
ALTER TABLE `newspost` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `newspost` MODIFY `seoTitle` TEXT;
ALTER TABLE `newspost` MODIFY `seoDescription` TEXT;
ALTER TABLE `partner` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `partner` MODIFY `description` TEXT;
ALTER TABLE `presidentmessage` MODIFY `position` TEXT NOT NULL;
ALTER TABLE `presidentmessage` MODIFY `message` TEXT NOT NULL;
ALTER TABLE `program` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `program` MODIFY `summary` TEXT NOT NULL;
ALTER TABLE `program` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `project` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `project` MODIFY `summary` TEXT NOT NULL;
ALTER TABLE `project` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `project` MODIFY `seoTitle` TEXT;
ALTER TABLE `project` MODIFY `seoDescription` TEXT;
ALTER TABLE `projectcategory` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `projectimage` MODIFY `altText` TEXT;
ALTER TABLE `registrationsubmission` MODIFY `notes` TEXT;
ALTER TABLE `resource` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `resource` MODIFY `description` TEXT;
ALTER TABLE `resourcecategory` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `service` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `service` MODIFY `summary` TEXT NOT NULL;
ALTER TABLE `service` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `service` MODIFY `seoTitle` TEXT;
ALTER TABLE `service` MODIFY `seoDescription` TEXT;
ALTER TABLE `tag` MODIFY `name` TEXT NOT NULL;
ALTER TABLE `teammember` MODIFY `role` TEXT NOT NULL;
ALTER TABLE `teammember` MODIFY `bio` TEXT;
ALTER TABLE `testimonial` MODIFY `role` TEXT;
ALTER TABLE `testimonial` MODIFY `quote` TEXT NOT NULL;
ALTER TABLE `volunteerapplication` MODIFY `skills` TEXT;
ALTER TABLE `volunteerapplication` MODIFY `message` TEXT;
