<#
    Archives the Next.js half of D:\nesim before it is deleted.

    The git repository root is D:\nesim\laravel, so everything outside it is
    unversioned and deleting it would otherwise be unrecoverable.

    D:\nesim\prisma.zip already holds a full backup, but verify-nextjs-backup.ps1
    found it was written at 12:41 while prisma/schema.prisma was last changed at
    16:26 - it predates the column widening, so its schema is stale. This makes a
    current one rather than relying on it.

    Two deliberate differences from Compress-Archive:

      * entry names use forward slashes. PowerShell 5.1's Compress-Archive writes
        backslashes, which most non-Windows unzip tools read as a single flat
        filename, restoring the whole tree into one directory. An archive whose
        only job is recovery should not depend on the tool that opens it.
      * node_modules, .next, .idea, vendor and the existing zips are left out.
        The first two are regenerated by npm install and npm run build, .idea is
        IDE-local, vendor is a stray Composer install at the project root rather
        than part of the Next.js app, and archiving a 277 MB zip into another zip
        is waste.

    Then every entry is read back and hashed against the live file, so a silent
    partial write cannot pass.

    powershell -ExecutionPolicy Bypass -File storage\framework\archive-nextjs.ps1
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$root = 'D:\nesim'
$dest = 'D:\nesim-nextjs-source.zip'

$excludeTopLevel = @(
    'laravel', 'node_modules', '.next', '.idea', '.git', 'vendor',
    'prisma.zip', 'next.config.zip', 'tsconfig.tsbuildinfo'
)

if (Test-Path -LiteralPath $dest) {
    Write-Host "Aborted: $dest already exists. Move or remove it and re-run." -ForegroundColor Red
    exit 1
}

$files = @()

foreach ($item in Get-ChildItem -LiteralPath $root -Force) {
    if ($excludeTopLevel -contains $item.Name) { continue }

    if ($item.PSIsContainer) {
        $files += Get-ChildItem -LiteralPath $item.FullName -Recurse -File -Force
    } else {
        $files += $item
    }
}

$bytes = ($files | Measure-Object Length -Sum).Sum

Write-Host ('{0} files, {1:N1} MB -> {2}' -f $files.Count, ($bytes / 1MB), $dest)

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$stream = [System.IO.File]::Open($dest, [System.IO.FileMode]::CreateNew)
$archive = New-Object System.IO.Compression.ZipArchive($stream, [System.IO.Compression.ZipArchiveMode]::Create)

try {
    foreach ($file in $files) {
        $relative = $file.FullName.Substring($root.Length + 1).Replace('\', '/')

        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
            $archive, $file.FullName, $relative, [System.IO.Compression.CompressionLevel]::Optimal
        ) | Out-Null
    }
} finally {
    $archive.Dispose()
    $stream.Dispose()
}

Write-Host ('  written: {0:N1} MB' -f ((Get-Item -LiteralPath $dest).Length / 1MB))
Write-Host ''
Write-Host '=== read every entry back and compare hashes ==='

$check = [System.IO.Compression.ZipFile]::OpenRead($dest)
$problems = @()
$verified = 0

try {
    $sha = [System.Security.Cryptography.SHA256]::Create()

    foreach ($entry in $check.Entries) {
        if ($entry.FullName.EndsWith('/')) { continue }

        $live = Join-Path $root ($entry.FullName -replace '/', '\')

        if (-not (Test-Path -LiteralPath $live)) {
            $problems += ('no live file for entry: ' + $entry.FullName)
            continue
        }

        $entryStream = $entry.Open()
        try {
            $archivedHash = [System.BitConverter]::ToString($sha.ComputeHash($entryStream)).Replace('-', '')
        } finally {
            $entryStream.Dispose()
        }

        if ($archivedHash -ne (Get-FileHash -LiteralPath $live -Algorithm SHA256).Hash) {
            $problems += ('hash differs: ' + $entry.FullName)
            continue
        }

        $verified++
    }
} finally {
    $check.Dispose()
}

Write-Host ('  {0} entries verified byte-identical' -f $verified)

if ($problems.Count -gt 0) {
    Write-Host 'FAILED:' -ForegroundColor Red
    $problems | Select-Object -First 20 | ForEach-Object { Write-Host ('  - ' + $_) -ForegroundColor Red }
    exit 1
}

if ($verified -ne $files.Count) {
    Write-Host ('FAILED: archived {0} files but verified {1}' -f $files.Count, $verified) -ForegroundColor Red
    exit 1
}

Write-Host ''
Write-Host '=== the file the stale backup was missing ==='

$probe = [System.IO.Compression.ZipFile]::OpenRead($dest)
try {
    $entry = $probe.Entries | Where-Object { $_.FullName -eq 'prisma/schema.prisma' }

    if (-not $entry) {
        Write-Host 'FAILED: prisma/schema.prisma is not in the archive.' -ForegroundColor Red
        exit 1
    }

    $entryStream = $entry.Open()
    try {
        $text = (New-Object System.IO.StreamReader($entryStream)).ReadToEnd()
    } finally {
        $entryStream.Dispose()
    }
} finally {
    $probe.Dispose()
}

$textWidths = ([regex]::Matches($text, '@db\.Text')).Count

Write-Host ('  prisma/schema.prisma archived, {0} @db.Text annotations' -f $textWidths)
Write-Host ('  live file has {0}' -f ([regex]::Matches((Get-Content -LiteralPath (Join-Path $root 'prisma\schema.prisma') -Raw), '@db\.Text')).Count)

Write-Host ''
Write-Host ('OK: {0} is a current, portable archive of the Next.js source.' -f $dest) -ForegroundColor Green
Write-Host 'It sits outside D:\nesim, so it survives the deletion it is insurance for.' -ForegroundColor Green
