/*
 * Widens every content column that Prisma declared as a bare `String`, which
 * MySQL stores as varchar(191).
 *
 * Why: sql_mode here has no STRICT_TRANS_TABLES, so MySQL truncates over-long
 * values silently instead of refusing them. seed.js writes three-language
 * locale JSON into these columns and prose into others, and 191 characters is
 * structurally too small for either — a scan found 33 rows across 12 tables
 * already cut off, four of them mid-JSON so the public About page prints raw
 * `{"en":"…","am":"በጥራት` and the timeline decodes to nothing.
 *
 * Two outputs, kept in step with each other:
 *   1. laravel/database/widen-content-columns.sql  — the ALTERs to run now
 *   2. prisma/schema.prisma                        — @db.Text on the same fields,
 *      so a future `prisma db push` agrees with the database instead of
 *      silently narrowing all of it back
 *
 * Only unindexed columns are listed. A UNIQUE slug cannot become TEXT without a
 * prefix length, and an InnoDB foreign key has to match the column it points at,
 * so every id, slug and relation scalar stays varchar(191).
 */

// laravel/package.json sets "type": "module", so this is ESM like the rest of
// the app's build scripts.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// storage/framework -> storage -> laravel -> the project root.
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/**
 * Prisma model => the fields holding prose, a locale document or a JSON array.
 * Table names are strtolower(model) throughout this schema, which is what the
 * Laravel models declare and what the SQL below relies on.
 */
const CONTENT = {
  AboutContent: ['heroTitle', 'heroSubtitle', 'storyTitle', 'storyBody', 'missionText', 'visionText', 'valuesText', 'timelineData'],
  BlogCategory: ['name'],
  BlogPost: ['title', 'excerpt', 'body', 'seoTitle', 'seoDescription'],
  ContactMessage: ['subject', 'message'],
  FaqItem: ['question', 'answer'],
  Gallery: ['title', 'description'],
  GalleryImage: ['altText'],
  GlobalSettings: ['tagline', 'address', 'footerText', 'copyrightText', 'seoTitle', 'seoDescription', 'seoKeywords', 'ctaText'],
  HeroSlide: ['title', 'subtitle', 'buttonText'],
  ImpactStat: ['label', 'description'],
  IslamicMessage: ['arabicText', 'translation'],
  Media: ['altText'],
  MembershipApplication: ['address', 'motivation', 'documents'],
  MembershipCategory: ['name', 'description', 'requirements', 'benefits'],
  NewsCategory: ['name'],
  NewsPost: ['title', 'excerpt', 'body', 'seoTitle', 'seoDescription'],
  Partner: ['name', 'description'],
  PresidentMessage: ['position', 'message'],
  Program: ['title', 'summary', 'body'],
  Project: ['title', 'summary', 'body', 'seoTitle', 'seoDescription'],
  ProjectCategory: ['name'],
  ProjectImage: ['altText'],
  RegistrationSubmission: ['notes'],
  Resource: ['title', 'description'],
  ResourceCategory: ['name'],
  Service: ['title', 'summary', 'body', 'seoTitle', 'seoDescription'],
  Tag: ['name'],
  TeamMember: ['role', 'bio'],
  Testimonial: ['role', 'quote'],
  VolunteerApplication: ['skills', 'message'],
};

/* ── 1. The SQL ───────────────────────────────────────────────────────────── */

// Nullability has to be restated on every MODIFY, or MySQL resets it to NULL.
const nullable = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'laravel', 'storage', 'framework', 'nullable.json'), 'utf8'),
);

const statements = [];

for (const [model, fields] of Object.entries(CONTENT)) {
  const table = model.toLowerCase();

  for (const field of fields) {
    const isNullable = nullable[`${table}.${field}`];

    if (isNullable === undefined) {
      throw new Error(`${table}.${field} is not a varchar column — check the list`);
    }

    statements.push(
      `ALTER TABLE \`${table}\` MODIFY \`${field}\` TEXT${isNullable ? '' : ' NOT NULL'};`,
    );
  }
}

const sql = `-- Widens the content columns Prisma declared as a bare String, which MySQL
-- stores as varchar(191) and silently truncates because sql_mode has no
-- STRICT_TRANS_TABLES. Generated by laravel/storage/framework/make-widen.js;
-- the matching @db.Text annotations were added to prisma/schema.prisma at the
-- same time, so the two agree.
--
-- Indexed columns are deliberately absent: a UNIQUE slug needs a prefix length
-- to become TEXT, and a foreign key must match the column it references.
--
-- ${statements.length} statements, all of them widenings — no data is lost by
-- running this, and it is safe to re-run.

${statements.join('\n')}
`;

fs.writeFileSync(path.join(ROOT, 'laravel', 'database', 'widen-content-columns.sql'), sql, 'utf8');

console.log(`wrote ${statements.length} ALTER statements`);

/* ── 2. prisma/schema.prisma ──────────────────────────────────────────────── */

const schemaPath = path.join(ROOT, 'prisma', 'schema.prisma');
let schema = fs.readFileSync(schemaPath, 'utf8');

let patched = 0;
let already = 0;
const missing = [];

for (const [model, fields] of Object.entries(CONTENT)) {
  const start = schema.indexOf(`model ${model} {`);

  if (start < 0) {
    missing.push(`model ${model}`);
    continue;
  }

  const end = schema.indexOf('\n}', start);
  const body = schema.slice(start, end);
  let next = body;

  for (const field of fields) {
    // `  title     String   @id @default(cuid())` — match the declaration line,
    // never a relation line, and never one that already carries a @db attribute.
    const line = new RegExp(`^(\\s+${field}\\s+String\\??\\s*)(@.*)?$`, 'm');
    const match = next.match(line);

    if (!match) {
      missing.push(`${model}.${field}`);
      continue;
    }

    if (match[2] && match[2].includes('@db.')) {
      already++;
      continue;
    }

    // Existing attributes (@default, @unique) are kept; @db.Text goes last, which
    // is where `prisma format` puts it.
    next = next.replace(line, (_all, head, rest) => `${head}${rest ? `${rest} ` : ''}@db.Text`);
    patched++;
  }

  schema = schema.slice(0, start) + next + schema.slice(end);
}

fs.writeFileSync(schemaPath, schema, 'utf8');

console.log(`schema.prisma: ${patched} fields annotated, ${already} already were`);

if (missing.length > 0) {
  console.log('COULD NOT MATCH:');
  missing.forEach((item) => console.log(`  ${item}`));
  process.exitCode = 1;
}
